### ISSUE TITLE
Gradient Support?

### ISSUE THREAD

**Issue by RobMayer** [mattdesl/gdx-fontpack#4]
Support for gradients would be awesome. Specifically ones that take into account the offsets of the glyph and interpolates between colors appropriately.

**Comment by RobMayer** [comment]
hate to be that guy, but bump?

**Comment by mattdesl** [comment]
I probably won't add this myself, but I do accept pull requests. :)

**Comment by RobMayer** [comment]
_cracks knuckles_ let's see how good my java-fu is.
